import { Menu, Phone, X } from 'lucide-react'
import { NavLink, Link, useLocation } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { company } from '../../content/company'
import { navigation } from '../../content/navigation'
import { useScrollProgress } from '../../hooks/useScrollProgress'
import { TopBar } from './TopBar'
export function Brand() { return <Link to="/" aria-label="1st Class Express home" className="leading-none"><span className="block font-display text-xl font-extrabold tracking-[-.08em] text-white sm:text-2xl">1ST CLASS</span><span className="block text-[.58rem] font-bold tracking-[.27em] text-gold">EXPRESS</span></Link> }
export function SiteHeader() { const [open, setOpen] = useState(false); const loc = useLocation(); const scrolled = useScrollProgress(); useEffect(() => setOpen(false), [loc.pathname]); const solid = scrolled || loc.pathname !== '/'; return <header className={`sticky top-0 z-40 transition-colors ${solid ? 'bg-charcoal shadow-lg' : 'bg-ink/90 backdrop-blur-md'}`}><TopBar/><div className="container-page flex min-h-18 items-center justify-between gap-4 py-3"><Brand/><nav className="hidden items-center gap-5 xl:flex" aria-label="Main navigation">{navigation.map(item => <NavLink key={item.to} to={item.to} className={({isActive}) => `text-xs font-bold uppercase tracking-[.12em] text-soft-grey hover:text-gold ${isActive ? 'text-gold' : ''}`} end={item.to === '/'}>{item.label}</NavLink>)}<Link className="button-primary min-h-10 py-2" to="/quote">Get a Quote</Link></nav><div className="flex items-center gap-2 xl:hidden"><a className="rounded-sm p-3 text-white" href={company.phoneHref} aria-label="Call 1st Class Express"><Phone size={20}/></a><button className="rounded-sm border border-white/30 p-3 text-white" type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open && <div className="border-t border-white/10 bg-charcoal xl:hidden"><nav className="container-page flex flex-col py-4" aria-label="Mobile navigation">{navigation.map(item => <NavLink key={item.to} to={item.to} className="border-b border-white/10 py-4 text-sm font-bold text-white">{item.label}</NavLink>)}<Link className="button-primary mt-4" to="/quote">Get a Quote</Link></nav></div>}</header> }
