import { Link } from 'react-router-dom'
import { PageHero } from '../components/common/PageHero'
import { SectionHeading } from '../components/common/SectionHeading'
import { SEO } from '../components/common/SEO'
import { Button } from '../components/common/Button'
import { company } from '../content/company'
import { fleetCategories } from '../content/fleet'
import { seo } from '../content/seo'
export function AboutPage() { return <><SEO {...seo.about}/><PageHero eyebrow="About us" title="A Service Commitment That Moves With You" copy="Australian-owned transport support for local, regional and interstate freight enquiries."/><section className="section"><div className="container-page grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Company overview" title="Practical support for freight requirements" copy="1st Class Express works with businesses and private customers seeking a reliable, professional transport partner. The focus is clear communication, appropriate scheduling and careful freight handling."/><p className="mt-6 leading-7 text-slate">The company’s approach is based on understanding the load, route and requested timeframe before coordinating a suitable transport solution.</p></div><div className="truck-fallback min-h-80 border border-gold/30"/></div></section><section className="section bg-charcoal text-white"><div className="container-page"><SectionHeading eyebrow="Core values" title="The principles behind every conversation" inverted/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{company.values.map((x,index)=><div className="border-t border-gold p-5" key={x}><span className="text-xs font-bold text-red">0{index+1}</span><h3 className="mt-7 text-2xl font-bold">{x}</h3></div>)}</div></div></section><section className="section"><div className="container-page grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Leadership and drivers" title="Experienced operational leadership" copy={`${company.director}, ${company.title}, leads 1st Class Express with a focus on dependable transport solutions, professional customer service and flexible logistics support.`}/><Link className="mt-6 inline-block font-bold text-red" to="/contact">Contact Div Sharma →</Link></div><div><h3 className="font-display text-2xl font-bold">Fleet flexibility</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{fleetCategories.map(x=><p key={x} className="border-l-2 border-gold pl-3 text-sm font-semibold">{x}</p>)}</div></div></div></section><section className="bg-red py-16 text-white"><div className="container-page flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-3xl font-extrabold">Let’s find a suitable transport solution.</h2><Button to="/quote" variant="dark">Request a Quote</Button></div></section></> }
